module.exports = (req, res) => {
  return res.render('index/details', {
    page: 'index/details',
    title: 'Ticket Details',
    includes: {
      external: {
        css: ['general', 'header', 'page'],
        js: ['header', 'page', 'serverRequest']
      }
    },
    event: {
      _id: '',
      type: '',
      name: 'Mor ve Ötesi',
      date: '23 Haz',
      hour: '21.00',
      organizer: 'Harun Tekin',
      campaign: '',
      place: 'Harbiye İstanbul',
      price: '',
      image: '/img/dolu_kadehi_ters_tut.png',
      description: 'Mor ve Ötesi, efsane yaz konserlerine Harbiye\'de devam ediyor. Bu güzel konser İstanbul\'un serin havasında dinleyicileri ile buluşacak.',
      rules: '- Etkinlik başladıktan sonra gelen seyircilerimizin satın almış oldukları koltuğa oturamama durumundan Biletix ve Organizatör sorumlu değildir. Organizatör firma ve Biletix geç kalan misafirler için koltuk garantisi vermez. Bu sebeple etkinliğe konser saatinden önce gelmenizi önemle rica ederiz. \n- 6 yaş altı giremez, 6 yaş üstü bilete tabidir.\n- Konser alanına dışarıdan yiyecek ve içecek alınmayacaktır.\n- Organizasyon şirketinin programda ve bilet fiyatlarında değişiklik yapma hakkı saklıdır.\n- Etkinlik mekanına kamera, fotoğraf makinası, ses cihazı vb. alınmayacaktır.\n- Satın alınan biletlerde iptal, iade ve değişiklik yapılmamaktadır. Aynı zamanda, bileti okutularak etkinlik alanına giriş yapan misafirler daha sonra etkinlik alanını terketmesi durumunda tekrar etkinlik alanına girişi yapamayacaktır.\n- Organizasyon firması, diğer misafirleri rahatsız eden/edecek nitelikte, uygun görmediği kişileri etkinlik için bilet bedelini iade etmek koşuluyla, etkinlik mekanına kişiyi almama hakkına sahiptir.\n- Etkinlik süresince kayıt yapılmasına izin verilmeyecektir. Seyirci, sanatçı yönetimi uygun gördüğü takdirde görsel-işitsel kayıt cihazlarına el konabileceğini kabul eder.\n- Etkinlik alanına yanıcı, patlayıcı (deodorant, sprey, parfüm, kolonya vb. gibi), parlayıcı, kesici ve delici olarak kullanılabilecek her türlü alet, termos, motor kaskı ve lazer imleci ile girilmemektedir.\n- Etkinlik mekanına evcil hayvan alınmamaktadır.',
      seating_plan: '',
      floor: '0.2 Atom',
      owners: '54',
      listed: '12',
      total_supply: '120'
    },
    tickets: [
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      },
      {
        _id: '',
        type: '',
        status: '',
        seat: '34',
        row: 'H',
        category: 'Üst Kat',
        campaign: '',
        price: '0.1 Atom',
        image: '/img/dolu_kadehi_ters_tut.png',
      }
    ]
  });
}